mod add_effect_pane;
mod add_pane;
mod arpeggiator_pane;
mod automation_pane;
mod checkpoint_list_pane;
mod command_palette_pane;
mod confirm_pane;
mod docs_pane;
mod eq_pane;
mod file_browser_pane;
mod frame_edit_pane;
mod groove_pane;
mod help_pane;
mod home_pane;
mod instrument_edit_pane;
mod instrument_pane;
mod instrument_picker_pane;
mod midi_settings_pane;
mod mixer_pane;
mod pane_switcher_pane;
mod piano_roll_pane;
mod project_browser_pane;
mod quit_prompt_pane;
mod sample_chopper_pane;
mod save_as_pane;
mod sequencer_pane;
mod server_pane;
mod track_pane;
mod tuner_pane;
mod vst_param_pane;
mod waveform_pane;

pub use add_effect_pane::AddEffectPane;
pub use add_pane::AddPane;
pub use arpeggiator_pane::ArpeggiatorPane;
pub use automation_pane::AutomationPane;
pub use checkpoint_list_pane::CheckpointListPane;
pub use command_palette_pane::CommandPalettePane;
pub use confirm_pane::{ConfirmPane, PendingAction};
pub use docs_pane::DocsPane;
pub use eq_pane::EqPane;
pub use file_browser_pane::FileBrowserPane;
pub use frame_edit_pane::FrameEditPane;
pub use groove_pane::GroovePane;
pub use help_pane::HelpPane;
pub use home_pane::HomePane;
pub use instrument_edit_pane::InstrumentEditPane;
pub use instrument_pane::InstrumentPane;
pub use instrument_picker_pane::InstrumentPickerPane;
pub use midi_settings_pane::MidiSettingsPane;
pub use mixer_pane::MixerPane;
pub use pane_switcher_pane::PaneSwitcherPane;
pub use piano_roll_pane::{PianoRollPane, ViewMode};
pub use project_browser_pane::ProjectBrowserPane;
pub use quit_prompt_pane::QuitPromptPane;
pub use sample_chopper_pane::SampleChopperPane;
pub use save_as_pane::SaveAsPane;
pub use sequencer_pane::SequencerPane;
pub use server_pane::ServerPane;
pub use track_pane::TrackPane;
pub use tuner_pane::TunerPane;
pub use vst_param_pane::VstParamPane;
pub use waveform_pane::WaveformPane;
